/**
 * LEARN: Prompt engineering is the practice of crafting inputs to LLMs
 * to get reliable, structured outputs. Key techniques used here:
 *
 * 1. ROLE ASSIGNMENT — "You are a senior engineer..." sets the model's
 *    "persona" and improves output quality significantly.
 *
 * 2. STRUCTURED OUTPUT — Asking for JSON with a defined schema means
 *    your code can reliably parse the response with JSON.parse() instead
 *    of trying to extract meaning from raw natural language.
 *
 * 3. CONSTRAINTS — Telling the model what NOT to do (e.g., "do not wrap
 *    in markdown code blocks") prevents common LLM formatting habits that
 *    break JSON.parse().
 *
 * 4. EXAMPLES — Showing the exact shape of the expected JSON helps the
 *    model understand the format without ambiguity.
 */

/**
 * Builds the full prompt to send to Gemini for code review.
 * @param {string} diff - The raw git diff of the pull request
 * @param {Object} prContext - { owner, repo, pull_number }
 * @returns {string} The complete prompt string
 */
function buildReviewPrompt(diff, prContext) {
  return `You are a senior software engineer conducting a thorough code review.
Your job is to review the following pull request diff and provide actionable, constructive feedback.

PULL REQUEST INFO:
- Repository: ${prContext.owner}/${prContext.repo}
- PR Number: #${prContext.pull_number}

GIT DIFF:
\`\`\`diff
${diff}
\`\`\`

INSTRUCTIONS:
1. Analyse the diff carefully — look for bugs, security issues, performance problems, poor naming, missing error handling, and style inconsistencies.
2. Also identify what was done well.
3. Be constructive and specific — reference actual line content from the diff.
4. Give a quality score from 1-10 (10 = production-ready, no issues).

RESPOND WITH ONLY VALID JSON — no markdown code blocks, no explanation outside the JSON.
Use exactly this structure:

{
  "summary": "2-3 sentence overall assessment of the PR",
  "score": 8,
  "positives": [
    "What was done well — be specific"
  ],
  "issues": [
    {
      "severity": "critical|major|minor|suggestion",
      "file": "path/to/file.js or 'general'",
      "description": "Clear description of the issue",
      "suggestion": "Concrete fix or improvement"
    }
  ]
}

Severity guide:
- critical: Will cause bugs or security vulnerabilities in production
- major: Significant code quality or maintainability problem  
- minor: Small issue, style, or missed best practice
- suggestion: Optional improvement or nice-to-have`;
}

/**
 * Formats the parsed Gemini JSON response into a clean
 * GitHub-flavoured Markdown comment for the PR.
 *
 * LEARN: GitHub PR comments support full Markdown — tables, bold,
 * code blocks, emojis. We use this to make the review easy to read
 * at a glance rather than dumping raw JSON.
 *
 * @param {Object} review - Parsed JSON from Gemini
 * @param {Object} prContext - { owner, repo, pull_number }
 * @returns {string} Formatted markdown string
 */
function formatReviewComment(review, prContext) {
  const scoreEmoji = review.score >= 8 ? '🟢' : review.score >= 5 ? '🟡' : '🔴';
  const severityEmoji = {
    critical: '🔴',
    major: '🟠',
    minor: '🟡',
    suggestion: '💡',
  };

  const issuesTable = review.issues?.length
    ? [
        '| Severity | File | Issue | Suggestion |',
        '|---|---|---|---|',
        ...review.issues.map(
          (i) =>
            `| ${severityEmoji[i.severity] || ''} ${i.severity} | \`${i.file}\` | ${i.description} | ${i.suggestion} |`
        ),
      ].join('\n')
    : '_No issues found._';

  const positivesList = review.positives?.length
    ? review.positives.map((p) => `- ${p}`).join('\n')
    : '_None noted._';

  return `## 🤖 AI Code Review

> Automated review powered by Google Gemini AI

**Overall Score:** ${scoreEmoji} **${review.score}/10**

**Summary:** ${review.summary}

---

### ✅ What's Good

${positivesList}

---

### 📋 Issues & Suggestions

${issuesTable}

---

<sub>Generated by [ai-code-reviewer](https://github.com/Chumani-Lalasa/ai-code-reviewer) · PR #${prContext.pull_number}</sub>`;
}

module.exports = { buildReviewPrompt, formatReviewComment };
